version: '3'

services:
  db:
    image: postgres:9.6
    container_name: postgres_django
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_app
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build: .
    container_name: celery_worker
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
      - web
    command: celery -A config worker --loglevel=info

volumes:
  pg_data:
