version: '3'

services:
  db:
    image: postgres:9.6
    container_name: postgres_django
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pg_data:
