# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
